services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - PYTHONUNBUFFERED=1
      - FLASK_DEBUG=0
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"